// packages/firebaseui-react/src/components/terms-and-privacy.tsx
import { getTranslation } from "@firebase-ui/core";
import { useConfig } from "../hooks";
import { Fragment } from "react";

export function TermsAndPrivacy() {
  const config = useConfig();

  if (!config.tosUrl && !config.privacyPolicyUrl) {
    return null;
  }

  const termsText = getTranslation(
    "labels",
    "termsOfService",
    config.translations,
    config.language
  );
  const privacyText = getTranslation(
    "labels",
    "privacyPolicy",
    config.translations,
    config.language
  );
  const termsAndPrivacyText = getTranslation(
    "messages",
    "termsAndPrivacy",
    config.translations,
    config.language
  );

  const parts = termsAndPrivacyText.split(/(\{tos\}|\{privacy\})/);

  return (
    <div className="text-text-muted text-xs text-start">
      {parts.map((part: string, index: number) => {
        if (part === "{tos}" && config.tosUrl) {
          return (
            <a
              key={index}
              href={config.tosUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-text-muted hover:underline text-xs"
            >
              {termsText}
            </a>
          );
        }
        if (part === "{privacy}" && config.privacyPolicyUrl) {
          return (
            <a
              key={index}
              href={config.privacyPolicyUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-text-muted hover:underline text-xs"
            >
              {privacyText}
            </a>
          );
        }
        return <Fragment key={index}>{part}</Fragment>;
      })}
    </div>
  );
}

// packages/angular/projects/firebaseui-angular/src/lib/components/terms-and-privacy/terms-and-privacy.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FirebaseUI } from '../../provider';
import { map } from 'rxjs/operators';

@Component({
  selector: 'fui-terms-and-privacy',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- <div class="text-text-muted text-xs text-start my-6" *ngIf="shouldShow | async">
      <ng-container *ngFor="let part of parts | async; let i = index">
        <a 
          *ngIf="part.type === 'tos' && (tosUrl | async)"
          [href]="tosUrl | async"
          target="_blank"
          rel="noopener noreferrer"
          class="text-text-muted hover:underline text-xs"
        >
          {{ termsText | async }}
        </a>
        <a 
          *ngIf="part.type === 'privacy' && (privacyPolicyUrl | async)"
          [href]="privacyPolicyUrl | async"
          target="_blank"
          rel="noopener noreferrer"
          class="text-text-muted hover:underline text-xs"
        >
          {{ privacyText | async }}
        </a>
        <ng-container *ngIf="part.type === 'text'">{{ part.content }}</ng-container>
      </ng-container>
    </div> -->
  `,
})
export class TermsAndPrivacyComponent {
  private ui = inject(FirebaseUI);

  // tosUrl = this.ui.config().pipe(
  //   map(config => config?.tosUrl)
  // );

  // privacyPolicyUrl = this.ui.config().pipe(
  //   map(config => config?.privacyPolicyUrl)
  // );

  // shouldShow = this.ui.config().pipe(
  //   map(config => !!(config?.tosUrl || config?.privacyPolicyUrl))
  // );

  termsText = this.ui.translation('labels', 'termsOfService');
  privacyText = this.ui.translation('labels', 'privacyPolicy');

  parts = this.ui.translation('messages', 'termsAndPrivacy').pipe(
    map((text) => {
      const parts = text.split(/({tos}|{privacy})/);
      return parts.map((part) => {
        if (part === '{tos}') {
          return { type: 'tos' };
        }
        if (part === '{privacy}') {
          return { type: 'privacy' };
        }
        return { type: 'text', content: part };
      });
    }),
  );
}
