// packages/firebaseui-react/src/auth/email-link-form.tsx
"use client";

import { useForm } from "@tanstack/react-form";
import { useAuth, useConfig, useTranslations } from "~/hooks";
import {
  FirebaseUIError,
  getTranslation,
  createEmailLinkFormSchema,
  fuiSendSignInLinkToEmail,
  fuiSignInWithEmailLink,
  fuiIsSignInWithEmailLink,
} from "@firebase-ui/core";
import { Button } from "../components/button";
import { FieldInfo } from "../components/field-info";
import { useEffect, useState } from "react";

export function EmailLinkForm() {
  const auth = useAuth();
  const { language, enableAutoUpgradeAnonymous } = useConfig();
  const translations = useTranslations();
  const [formError, setFormError] = useState<string | null>(null);
  const [emailSent, setEmailSent] = useState(false);

  const emailLinkFormSchema = createEmailLinkFormSchema(translations);

  const form = useForm({
    defaultValues: {
      email: "",
    },
    validators: {
      onBlur: emailLinkFormSchema,
      onSubmit: emailLinkFormSchema,
    },
    onSubmit: async ({ value }) => {
      setFormError(null);
      try {
        await fuiSendSignInLinkToEmail(auth, value.email, {
          translations,
          language,
          enableAutoUpgradeAnonymous,
        });
        setEmailSent(true);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          setFormError(error.message);
        }
      }
    },
  });

  // Handle email link sign-in if URL contains the link
  useEffect(() => {
    const completeSignIn = async () => {
      try {
        const email = window.localStorage.getItem("emailForSignIn");
        if (!email) return;

        if (fuiIsSignInWithEmailLink(auth, window.location.href)) {
          await fuiSignInWithEmailLink(auth, email, window.location.href, {
            translations,
            language,
            enableAutoUpgradeAnonymous,
          });
          window.localStorage.removeItem("emailForSignIn");
        }
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          setFormError(error.message);
        }
      }
    };

    void completeSignIn();
  }, [auth, translations]);

  if (emailSent) {
    return (
      <div className="fui-form">
        <div className="text-center mb-4">
          {getTranslation("messages", "signInLinkSent", translations, language)}
        </div>
      </div>
    );
  }

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <div className="fui-form__group">
        <form.Field
          name="email"
          children={(field) => (
            <>
              <label className="fui-form__label" htmlFor={field.name}>
                {getTranslation(
                  "labels",
                  "emailAddress",
                  translations,
                  language
                )}
              </label>
              <input
                className={`fui-form__input ${
                  field.state.meta.errors.length ? "fui-form__input--error" : ""
                }`}
                id={field.name}
                name={field.name}
                type="email"
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
              <FieldInfo field={field} />
            </>
          )}
        />
      </div>

      <div className="flex flex-col gap-2">
        <Button type="submit" variant="primary">
          {getTranslation("labels", "sendSignInLink", translations, language)}
        </Button>
      </div>

      {formError && (
        <div
          className="fui-form__error"
          style={{ textAlign: "center", marginTop: "var(--fui-spacing-sm)" }}
        >
          {formError}
        </div>
      )}
    </form>
  );
}

// packages/angular/projects/firebaseui-angular/src/lib/auth/forms/email-link-form/email-link-form.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { injectForm, TanStackField } from '@tanstack/angular-form';
import { FirebaseUi } from '../../../provider';
import { Auth } from '@angular/fire/auth';
import { map } from 'rxjs/operators';
import { ButtonComponent } from '../../../components/button/button.component';
import { TermsAndPrivacyComponent } from '../../../components/terms-and-privacy/terms-and-privacy.component';
import { createEmailLinkFormSchema, FirebaseUIError, fuiCompleteEmailLinkSignIn, fuiSendSignInLinkToEmail } from '@firebase-ui/core';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'fui-email-link-form',
  standalone: true,
  imports: [CommonModule, TanStackField, ButtonComponent, TermsAndPrivacyComponent],
  template: `
    <div *ngIf="emailSent" class="fui-form">
      {{ emailSentMessage | async }}
    </div>
    <form *ngIf="!emailSent" (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <ng-container
          [tanstackField]="form"
          name="email"
          #email="field"
        >
          <label [for]="email.api.name">
            <span>{{ emailLabel | async }}</span>
            <input
              type="email"
              [id]="email.api.name"
              [name]="email.api.name"
              [value]="email.api.state.value"
              (blur)="email.api.handleBlur()"
              (input)="email.api.handleChange($any($event).target.value)"
              [attr.aria-invalid]="!!email.api.state.meta.errors.length"
            />
            <span 
              role="alert" 
              aria-live="polite" 
              class="fui-form__error" 
              *ngIf="!!email.api.state.meta.errors.length"
            >
              {{ email.api.state.meta.errors.join(', ') }}
            </span>
          </label>
        </ng-container>
      </fieldset>

      <fui-terms-and-privacy></fui-terms-and-privacy>

      <fieldset>
        <fui-button type="submit">
          {{ sendSignInLinkLabel | async }}
        </fui-button>
        <div class="fui-form__error" *ngIf="formError">{{ formError }}</div>
      </fieldset>
    </form>
  `
})
export class EmailLinkFormComponent implements OnInit {
  private ui = inject(FirebaseUi);
  private auth = inject(Auth);
  private schema = this.ui.config().pipe(
    map(config => createEmailLinkFormSchema(config?.translations))
  );

  formError: string | null = null;
  emailSent = false;

  form = injectForm({
    defaultValues: {
      email: ''
    },
    onSubmit: async ({ value }) => {
      this.formError = null;
      try {
        const config = await firstValueFrom(this.ui.config());
        
        await fuiSendSignInLinkToEmail(
          this.auth, 
          value.email, 
          {
            translations: config?.translations,
            language: config?.language,
            enableAutoUpgradeAnonymous: config?.enableAutoUpgradeAnonymous
          }
        );
        this.emailSent = true;
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          this.formError = error.message;
          return;
        }

        console.error(error);
        this.formError = await firstValueFrom(this.ui.translation('errors', 'unknownError'));
      }
    }
  });

  constructor() {
    this.schema.subscribe(schema => {
      this.form.update({
        validators: {
          onSubmit: schema,
          onBlur: schema
        }
      });
    });
  }

  ngOnInit() {
    // Handle email link sign-in if URL contains the link
    this.completeSignIn();
  }

  private async completeSignIn() {
    try {
      const config = await firstValueFrom(this.ui.config());
      
      await fuiCompleteEmailLinkSignIn(
        this.auth, 
        window.location.href, 
        {
          translations: config?.translations,
          language: config?.language,
          enableAutoUpgradeAnonymous: config?.enableAutoUpgradeAnonymous,
          enableHandleExistingCredential: config?.enableHandleExistingCredential
        }
      );
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        this.formError = error.message;
      }
    }
  }

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  get emailLabel() {
    return this.ui.translation('labels', 'emailAddress');
  }

  get sendSignInLinkLabel() {
    return this.ui.translation('labels', 'sendSignInLink');
  }

  get emailSentMessage() {
    return this.ui.translation('messages', 'signInLinkSent');
  }
}
