// packages/firebaseui-react/src/auth/screens/sign-up-auth-screen.tsx
import { Card } from "../../components/card";
import { CardHeader } from "../../components/card-header";
import { CardTitle } from "../../components/card-title";
import { CardSubtitle } from "../../components/card-subtitle";
import { RegisterForm } from "../forms/register-form";
import { useConfig, useTranslations } from "~/hooks";
import { getTranslation } from "@firebase-ui/core";
import { Divider } from "~/components/divider";

export interface SignUpAuthScreenProps {
  onBackToSignInClick?: () => void;
  children?: React.ReactNode | React.ReactNode[];
}

export function SignUpAuthScreen({
  onBackToSignInClick,
  children,
}: SignUpAuthScreenProps) {
  const { language } = useConfig();
  const translations = useTranslations();

  const titleText = getTranslation("labels", "register", translations, language);
  const subtitleText = getTranslation(
    "prompts",
    "enterDetailsToCreate",
    translations,
    language
  );

  return (
    <div className="fui-screen">
      <Card>
        <CardHeader>
          <CardTitle>{titleText}</CardTitle>
          <CardSubtitle>{subtitleText}</CardSubtitle>
        </CardHeader>
        <RegisterForm onBackToSignInClick={onBackToSignInClick} />
        {children ? (
          <>
            <Divider />
            <div className="space-y-4">{children}</div>
          </>
        ) : null}
      </Card>
    </div>
  );
}

// packages/angular/projects/firebaseui-angular/src/lib/auth/screens/sign-up-auth-screen/sign-up-auth-screen.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardSubtitleComponent } from '../../../components/card/card.component';
import { DividerComponent } from '../../../components/divider/divider.component';

@Component({
  selector: 'fui-sign-up-auth-screen',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    DividerComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardSubtitleComponent,
  ],
  template: `
    <div class="fui-screen">
      <fui-card>
        <fui-card-header>
          <fui-card-title>TODO</fui-card-title>
          <fui-card-subtitle>TODO DESC</fui-card-subtitle>
        </fui-card-header>
        <!-- <fui-register-form (backToSignInClick)="onBackToSignInClick.emit()"></fui-register-form> -->
        <ng-container *ngIf="hasContent">
          <fui-divider>
           TODO: Add divider
          </fui-divider>
          <div class="space-y-4">
            <ng-content></ng-content>
          </div>
        </ng-container>
      </fui-card>
    </div>
  `
})
export class SignUpAuthScreenComponent {
  @Output() onBackToSignInClick = new EventEmitter<void>();

  // titleText: string;
  // subtitleText: string;
  translations: any;
  // language: string;

  get hasContent(): boolean {
    // const element = this.elementRef.nativeElement;
    // return element.childNodes.length > 0;
    return false;
  }

  // constructor(
  //   private configService: ConfigService,
  //   private elementRef: ElementRef
  // ) {
  //   this.language = this.configService.language;
  //   this.translations = this.configService.translations;

  //   this.titleText = getTranslation(
  //     'labels',
  //     'register',
  //     this.translations,
  //     this.language
  //   );
    
  //   this.subtitleText = getTranslation(
  //     'prompts',
  //     'enterDetailsToCreate',
  //     this.translations,
  //     this.language
  //   );
  // }
}
