// packages/angular/projects/firebaseui-angular/src/lib/auth/screens/phone-auth-screen/phone-auth-screen.component.ts
import { Component, ContentChildren, inject, Input, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardSubtitleComponent } from '../../../components/card/card.component';
import { FirebaseUi } from '../../../provider';
import { PhoneFormComponent } from '../../forms/phone-form/phone-form.component';
import { DividerComponent } from '../../../components/divider/divider.component';

@Component({
  selector: 'fui-phone-auth-screen',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardSubtitleComponent,
    PhoneFormComponent,
    DividerComponent,
  ],
  template: `
    <div class="fui-screen">
      <fui-card>
        <fui-card-header>
          <fui-card-title>{{ titleText | async }}</fui-card-title>
          <fui-card-subtitle>{{ subtitleText | async }}</fui-card-subtitle>
        </fui-card-header>
        <fui-phone-form [resendDelay]="resendDelay"></fui-phone-form>
        
        <ng-container *ngIf="hasContent">
          <fui-divider>{{ dividerOrLabel | async }}</fui-divider>
          <div class="space-y-4">
            <ng-content></ng-content>
          </div>
        </ng-container>
      </fui-card>
    </div>
  `
})
export class PhoneAuthScreenComponent {
  private ui = inject(FirebaseUi);
  
  @Input() resendDelay = 30;
  @ContentChildren('*') content!: QueryList<any>;

  get hasContent(): boolean {
    return this.content && this.content.length > 0;
  }

  get titleText() {
    return this.ui.translation('labels', 'signIn');
  }

  get subtitleText() {
    return this.ui.translation('prompts', 'signInToAccount');
  }

  get dividerOrLabel() {
    return this.ui.translation('messages', 'dividerOr');
  }
}

// packages/firebaseui-react/src/auth/screens/phone-auth-screen.tsx
import type { PropsWithChildren } from "react";
import { getTranslation } from "@firebase-ui/core";
import { Divider } from "~/components/divider";
import { useUI } from "~/hooks";
import {
  Card,
  CardHeader,
  CardSubtitle,
  CardTitle,
} from "../../components/card";
import { PhoneForm } from "../forms/phone-form";

export type PhoneAuthScreenProps = PropsWithChildren<{
  resendDelay?: number;
}>;

export function PhoneAuthScreen({
  children,
  resendDelay,
}: PhoneAuthScreenProps) {
  const ui = useUI();

  const titleText = getTranslation(ui, "labels", "signIn");
  const subtitleText = getTranslation(ui, "prompts", "signInToAccount");

  return (
    <div className="fui-screen">
      <Card>
        <CardHeader>
          <CardTitle>{titleText}</CardTitle>
          <CardSubtitle>{subtitleText}</CardSubtitle>
        </CardHeader>
        <PhoneForm resendDelay={resendDelay} />
        {children ? (
          <>
            <Divider>{getTranslation(ui, "messages", "dividerOr")}</Divider>
            <div className="space-y-4">{children}</div>
          </>
        ) : null}
      </Card>
    </div>
  );
}
