// packages/angular/projects/firebaseui-angular/src/lib/auth/screens/sign-in-auth-screen/sign-in-auth-screen.component.ts
import { Component, ContentChildren, EventEmitter, inject, Output, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardSubtitleComponent } from '../../../components/card/card.component';
import { FirebaseUi } from '../../../provider';
import { EmailPasswordFormComponent } from '../../forms/email-password-form/email-password-form.component';
import { DividerComponent } from '../../../components/divider/divider.component';

@Component({
  selector: 'fui-sign-in-auth-screen',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardSubtitleComponent,
    EmailPasswordFormComponent,
    DividerComponent,
  ],
  template: `
    <div class="fui-screen">
      <fui-card>
        <fui-card-header>
          <fui-card-title>{{ titleText | async }}</fui-card-title>
          <fui-card-subtitle>{{ subtitleText | async }}</fui-card-subtitle>
        </fui-card-header>
        <fui-email-password-form 
          (onForgotPasswordClick)="onForgotPasswordClick.emit()" 
          (onRegisterClick)="onRegisterClick.emit()"
        ></fui-email-password-form>
        
        <ng-container *ngIf="hasContent">
          <fui-divider>{{ dividerOrLabel | async }}</fui-divider>
          <div class="space-y-4">
            <ng-content></ng-content>
          </div>
        </ng-container>
      </fui-card>
    </div>
  `
})
export class SignInAuthScreenComponent {
  private ui = inject(FirebaseUi);
  
  @Output() onForgotPasswordClick = new EventEmitter<void>();
  @Output() onRegisterClick = new EventEmitter<void>();
  @ContentChildren('*') content!: QueryList<any>;

  get hasContent(): boolean {
    return this.content && this.content.length > 0;
  }

  get titleText() {
    return this.ui.translation('labels', 'signIn');
  }

  get subtitleText() {
    return this.ui.translation('prompts', 'signInToAccount');
  }

  get dividerOrLabel() {
    return this.ui.translation('messages', 'dividerOr');
  }
}

// packages/firebaseui-react/src/auth/screens/sign-in-auth-screen.tsx
import { Card } from "../../components/card";
import { CardHeader } from "../../components/card-header";
import { CardTitle } from "../../components/card-title";
import { CardSubtitle } from "../../components/card-subtitle";
import { EmailPasswordForm } from "../forms/email-password-form";
import { useConfig, useTranslations } from "~/hooks";
import { getTranslation } from "@firebase-ui/core";
import { Divider } from "~/components/divider";

export interface SignInAuthScreenProps {
  onForgotPasswordClick?: () => void;
  onRegisterClick?: () => void;
  children?: React.ReactNode | React.ReactNode[];
}

export function SignInAuthScreen({
  onForgotPasswordClick,
  onRegisterClick,
  children,
}: SignInAuthScreenProps) {
  const { language } = useConfig();
  const translations = useTranslations();

  const titleText = getTranslation("labels", "signIn", translations, language);
  const subtitleText = getTranslation(
    "prompts",
    "signInToAccount",
    translations,
    language
  );

  return (
    <div className="fui-screen">
      <Card>
        <CardHeader>
          <CardTitle>{titleText}</CardTitle>
          <CardSubtitle>{subtitleText}</CardSubtitle>
        </CardHeader>
        <EmailPasswordForm
          onForgotPasswordClick={onForgotPasswordClick}
          onRegisterClick={onRegisterClick}
        />
        {children ? (
          <>
            <Divider />
            <div className="space-y-4">{children}</div>
          </>
        ) : null}
      </Card>
    </div>
  );
}
