// packages/firebaseui-react/src/auth/screens/oauth-screen.tsx
import { Card } from "../../components/card";
import { CardHeader } from "../../components/card-header";
import { CardTitle } from "../../components/card-title";
import { CardSubtitle } from "../../components/card-subtitle";
import { useConfig, useTranslations } from "~/hooks";
import { getTranslation } from "@firebase-ui/core";

export interface OAuthAuthScreenProps {
  children: React.ReactNode | React.ReactNode[];
}

export function OAuthScreen({
  children,
}: OAuthAuthScreenProps) {
  const { language } = useConfig();
  const translations = useTranslations();

  // TODO: Translations for oauth providers
  const titleText = getTranslation("labels", "signIn", translations, language);
  const subtitleText = getTranslation(
    "prompts",
    "signInToAccount",
    translations,
    language
  );

  return (
    <div className="fui-screen">
      <Card>
        <CardHeader>
          <CardTitle>{titleText}</CardTitle>
          <CardSubtitle>{subtitleText}</CardSubtitle>
        </CardHeader>
        {children}
      </Card>
    </div>
  );
}

// packages/angular/projects/firebaseui-angular/src/lib/auth/screens/oauth-screen/oauth-screen.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardSubtitleComponent } from '../../../components/card/card.component';
import { FirebaseUi } from '../../../provider';
import { TermsAndPrivacyComponent } from '../../../components/terms-and-privacy/terms-and-privacy.component';

@Component({
  selector: 'fui-oauth-screen',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardSubtitleComponent,
    TermsAndPrivacyComponent,
  ],
  template: `
    <div class="fui-screen">
      <fui-card>
        <fui-card-header>
          <fui-card-title>{{ titleText | async }}</fui-card-title>
          <fui-card-subtitle>{{ subtitleText | async }}</fui-card-subtitle>
        </fui-card-header>
        <ng-content></ng-content>
        <fui-terms-and-privacy></fui-terms-and-privacy>
      </fui-card>
    </div>
  `
})
export class OAuthScreenComponent {
  private ui = inject(FirebaseUi);

  get titleText() {
    return this.ui.translation('labels', 'signIn');
  }

  get subtitleText() {
    return this.ui.translation('prompts', 'signInToAccount');
  }
}
