// packages/firebaseui-react/src/auth/screens/password-reset-screen.tsx
import { getTranslation } from "@firebase-ui/core";
import { useUI } from "~/hooks";
import {
  Card,
  CardHeader,
  CardSubtitle,
  CardTitle,
} from "../../components/card";
import { ForgotPasswordForm } from "../forms/forgot-password-form";

export type PasswordResetScreenProps = {
  onBackToSignInClick?: () => void;
};

export function PasswordResetScreen({
  onBackToSignInClick,
}: PasswordResetScreenProps) {
  const ui = useUI();

  const titleText = getTranslation(ui, "labels", "resetPassword");
  const subtitleText = getTranslation(ui, "prompts", "enterEmailToReset");

  return (
    <div className="fui-screen">
      <Card>
        <CardHeader>
          <CardTitle>{titleText}</CardTitle>
          <CardSubtitle>{subtitleText}</CardSubtitle>
        </CardHeader>
        <ForgotPasswordForm onBackToSignInClick={onBackToSignInClick} />
      </Card>
    </div>
  );
}

// packages/angular/projects/firebaseui-angular/src/lib/auth/screens/password-reset-screen/password-reset-screen.component.ts
import { Component, EventEmitter, inject, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardSubtitleComponent } from '../../../components/card/card.component';
import { FirebaseUi } from '../../../provider';
import { ForgotPasswordFormComponent } from '../../forms/forgot-password-form/forgot-password-form.component';

@Component({
  selector: 'fui-password-reset-screen',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardSubtitleComponent,
    ForgotPasswordFormComponent,
  ],
  template: `
    <div class="fui-screen">
      <fui-card>
        <fui-card-header>
          <fui-card-title>{{ titleText | async }}</fui-card-title>
          <fui-card-subtitle>{{ subtitleText | async }}</fui-card-subtitle>
        </fui-card-header>
        <fui-forgot-password-form 
          (onBackToSignInClick)="onBackToSignInClick.emit()"
        ></fui-forgot-password-form>
      </fui-card>
    </div>
  `
})
export class PasswordResetScreenComponent {
  private ui = inject(FirebaseUi);
  
  @Output() onBackToSignInClick = new EventEmitter<void>();

  get titleText() {
    return this.ui.translation('labels', 'resetPassword');
  }

  get subtitleText() {
    return this.ui.translation('prompts', 'enterEmailToReset');
  }
}
